In [2]:
#find out imilar elements in another array
import numpy as np

a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.where(a == b)

(array([1, 3, 5, 7], dtype=int64),)

In [17]:
# print odd no in array 
import numpy as np

a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

a[a % 2 == 1]
    
    

array([1, 3, 5, 7, 9])

In [20]:
#convert 1d array to 2d array
import numpy as np

a= np.array([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
a.reshape(2,-1)


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [34]:
#extract all elements from given range betn 5t010
import numpy as np

a= np.array([2, 6, 1, 9, 10, 3, 27])

index = np.where((a >= 5) & (a <= 10))
a[index]


array([ 6,  9, 10])

In [36]:
#to reverse the rows of a 2D array?

import numpy as np

i = np.arange(9).reshape(3,3)
print(i)

i[: : -1]


[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

In [39]:
#Convert array_of_arrays into a flat linear 1d array.
import numpy as np

i = np.arange(3)
j = np.arange(3,7)
k = np.arange(7,10)

array = np.array([i, j, k])
print('array: ', array)

arr_2d = np.concatenate(array)
print(arr_2d)



array:  [array([0, 1, 2]) array([3, 4, 5, 6]) array([7, 8, 9])]
[0 1 2 3 4 5 6 7 8 9]


In [44]:
#to find the duplicate records in a numpy array
import numpy as np
np.random.seed(100)
a = np.random.randint(0, 5, 10)
print('Array: ', a)
#making true value array
out = np.full(a.shape[0], True)
print(out)
# index for unique value
unique_positions = np.unique(a, return_index=True)[1]
print(unique_positions)
# Mark those positions as False
out[unique_positions] = False
print(out)


Array:  [0 0 3 0 2 4 2 2 2 2]
[ True  True  True  True  True  True  True  True  True  True]
[0 4 2 5]
[False  True False  True False False  True  True  True  True]


In [45]:
import numpy as np

a = np.array([1,2,3,np.nan,5,6,7,np.nan])

a[~np.isnan(a)]


array([1., 2., 3., 5., 6., 7.])

In [46]:
#calculate euclidean distance
import numpy as np

point1 = np.array((1, 2, 3)) 
point2 = np.array((1, 1, 1)) 
  
# calculating Euclidean distance 
# using linalg.norm() 
dist = np.linalg.norm(point1 - point2) 
  
# printing Euclidean distance 
print(dist) 

2.23606797749979


In [56]:
#Subtract the 1d array b_1d from the 2d array a_2d, such that each item of b_1d subtracts from respective row of a_2d.


import numpy as np

a_2d = np.array([[3,3,3],[4,4,4],[5,5,5]])
b_1d = np.array([1,1,1]
subtraction = a_2d - b_1d[:,None]
print(subtraction)



SyntaxError: invalid syntax (<ipython-input-56-ba5e2711ea36>, line 8)

In [55]:
import numpy as np

np.random.seed(101) 
arr = np.random.randint(1,4, size=6)
arr
def one_hot_encodings(arr):
    uniqs = np.unique(arr)
    out = np.zeros((arr.shape[0], uniqs.shape[0]))
    for i, k in enumerate(arr):
        out[i, k-1] = 1
    return out

one_hot_encodings(arr)


array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [63]:
#How to swap two columns in a 2d numpy array?
arr = np.arange(9).reshape(3,3)
print(arr)
swap_arr = arr[:, [1,0,2]]
swap_arr

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

In [65]:
#swap two rows in array
arr = np.arange(9).reshape(3,3)
print(arr)
rowswaparr = arr[[1,0,2], :]
print(rowswaparr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[3 4 5]
 [0 1 2]
 [6 7 8]]


In [68]:
#create 2d arrays using random float no
import numpy as np
array = np.arange(9).reshape(3,3)
print(array)
rand_arr = np.random.uniform(5,10, size=(5,3))
print(rand_arr)


[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[9.32549908 9.15138856 7.69080725]
 [9.61234686 5.4857324  5.51423747]
 [8.50753648 9.45239935 5.7978015 ]
 [6.37786272 8.36245765 5.82151562]
 [8.50685568 7.43817611 8.40338884]]


In [70]:
#print only 3 decimal points
j = np.random.random([5,3])

print(j)

# Limit to 3 decimal places
np.set_printoptions(precision=3)
j[:4]


[[0.52154819 0.04339669 0.2239366 ]
 [0.57520509 0.12043366 0.50011671]
 [0.13800957 0.0528084  0.17827692]
 [0.44236813 0.87758732 0.94926413]
 [0.47816742 0.46111934 0.63728903]]


array([[0.522, 0.043, 0.224],
       [0.575, 0.12 , 0.5  ],
       [0.138, 0.053, 0.178],
       [0.442, 0.878, 0.949]])

In [81]:
#Limit the number of items printed in python numpy array a to a maximum of 8 elements
import numpy as np
a = np.arange(20)
print(a)

np.set_printoptions(threshold=8)
b = np.arange(20)
print(b)

[ 0  1  2 ... 17 18 19]
[ 0  1  2 ... 17 18 19]
